### ISSUE TITLE
Limit of taxas in brranching

### ISSUE THREAD

**Issue by aeltonbg** [ropensci/brranching#13]
My name is Aelton Giroldo, and I am PhD student in Ecology.

I am trying to build a phylogenetic tree using brranching. 

My data set had 11438 species.

I wrote the code as below:

``` r
>tax<- read.delim("taxa.txt")
>taxa1k<-unique(as.character(tax$Taxa[1:1000]))#Same format as example in brranching - 200 spp
>tree1k<-phylomatic(taxa=taxa1k,  get = "POST",method = "phylomatic", storedtree = "R20120829")
No encoding supplied: defaulting to UTF-8.
NOTE: 9 taxa not matched: ....
>tree1k#Returns
Phylogenetic tree with 991 tips and 190 internal nodes.

Tip labels:
    abarema_cochliacarpos, abarema_langsdorffii, abarema_villosa, albizia_inundata, albizia_niopoides, albizia_pedicellaris, ...
Node labels:
    magnoliales_to_asterales, poales_to_asterales, eudicots, , , , ...
Rooted; no branch lengths.
```

I did more 3 trees just increasing the species number (taxa).

``` r
>taxa4k<-unique(as.character(tax$Taxa[1:4000]))#Just increasing to 4000 the number of species.
>tree4k<-phylomatic(taxa=taxa4k,  get = "POST",method = "phylomatic", storedtree = "R20120829")#Until here ok, I had the tree.
No encoding supplied: defaulting to UTF-8.
NOTE: 73 taxa not matched: .....
> tree4k

Phylogenetic tree with 3927 tips and 552 internal nodes.

Tip labels:
    bulbostylis_brevifolia, bulbostylis_capillaris, bulbostylis_carajana, bulbostylis_circinata, bulbostylis_conifera, bulbostylis_conostachya, ...
Node labels:
    magnoliales_to_asterales, poales_to_asterales, eudicots, , , , ...

Rooted; no branch lengths.
```

So, the next tree is stucked, I don't know if there is a limit of taxa, I hope not!

``` r
taxa5k<-unique(as.character(tax$Taxa[1:5000]))#Just increasing to 5000 the number of species.
tree5k<-phylomatic(taxa=taxa5k,  get = "POST",method = "phylomatic", storedtree = "R20120829")
No encoding supplied: defaulting to UTF-8.
> tree5#Problem... return the error!

Phylogenetic tree with 0 tips and  internal nodes.

Tip labels:
NULL
Error in tabulate(phy$edge[, 1]) : 'bin' need to be numeric or factor.
```

Could anyone tell me what I am doing wrong in the code? Or really is there taxa limit in brranching?

Thanks! Regards

**Comment by sckott** [comment]
thanks for your bug report @aeltonbg - short answer is: there is a limit on number of taxa, it is 5000, see http://phylodiversity.net/phylomatic/html/documentation.html - I don't think i have that in the docs (or maybe Cam just added that recently).   I'll add that to the docs. He lists alternatives as using phylocom locally, or using the scripts behind the phylomatic web service locally.  An R option would be ideal though, so I'm looking into an R solution for really large taxon lists.

**Comment by sckott** [comment]
Playing with local usage for bigger data, stumbling block though, asked camwebb/phylomatic-ws#3

**Comment by aeltonbg** [comment]
Well,

I tried here again, and discovered that the number of taxas allowed is not 5,000, even 4,999 generated the same error.

So I started to decrease the number, and works when the taxas number is around 4,100.

I am trying to find a solution... breaking the tree in 3 different ones could be the solution, and after I could merge them.

The other problem that I will find after is how to insert the nodes date. I suspect that bladj will get stuck, once the large data. But let me see!

Thanks @sckott for the quickly answer.

**Comment by sckott** [comment]
I imagine the 5000 limit is most likely not actually 5000, but the scripts probably test for some total character length, and this depends on how long each name is - just guessing though.

**Comment by sckott** [comment]
@aeltonbg okay, after some ugly hacking, this may work for you (works for me at least)
- reinstall from github `devtools::install_github("ropensci/brranching")`
- download the local version of phylomatic, either `git clone https://github.com/camwebb/phylomatic-ws.git` or download the zip file on https://github.com/camwebb/phylomatic-ws (button towards the right) and unzip it
- use `phylomatic_local()`, and give the path to where the folder `phylomatic-ws` is located on your computer. 
- You'll need two command line utilities called `awk` and `gawk`. The function checks for those and will stop with message if you don't have them. 
- works for me with > 5000
- let me know if it works

**Comment by aeltonbg** [comment]
Hello @sckott,

Thanks again by help!
- I am trying here, and as you told my function stopped because I don't have the awk and gawk. I never hear about these command lines.
  In summary, I don't have the knowledge in how to do these command lines. If you have some light about how to do it I will appreciate a lot. Any script as example will be perfect!
- I am really trying to understand all the codes in R, reading about awk and gawk, but it is not a easy steps.

thanks again
regards

**Comment by sckott** [comment]
what operating system are you on?

**Comment by aeltonbg** [comment]
@sckott 
I am using windows 10!

**Comment by sckott** [comment]
There's a few ways to install. I don't use windows so I don't know the best way, can try 

https://github.com/bmatzelle/gow
http://scoop.sh/

illl test on windows later today

**Comment by sckott** [comment]
actually, try this one first https://msys2.github.io/

**Comment by aeltonbg** [comment]
I install the last! and now, is just run the script in R, or need to write some code?

**Comment by sckott** [comment]
make sure you have downloaded latest from github `devtools::install_github("ropensci/brranching")` and use `phylomatic_local()`, and give the path to where the folder `phylomatic-ws` is located on your computer.

**Comment by aeltonbg** [comment]
Still not working. Even after install and run the third https://msys2.github.io/  it didn't work!

Error: awk is missing, install it first.

I am trying to install awk and gawk using other website.

Are you using linux?

thanks

**Comment by aeltonbg** [comment]
Finally I install awk!

I am using windows 10. So, if someone had the same problem to install it, the steps are:

Step 1: open windows PowerShell as admin.
Step 2: http://scoop.sh/ use the link that @sckott send above or go directly to step 3.
Step 3: set-executionpolicy unrestricted -s cu , answer YES if ask something.
Step 4: iex (new-object net.webclient).downloadstring('https://get.scoop.sh') , after it your windows powershell will close. Open it again as in Step 1
Step 5: scoop install gawk , now you had the gawk installed in your PC. Back to R and work.

@sckott the problem that I had now is that:

> library(brranching)
> tax<- read.delim("taxa.txt")
> taxa<-unique(as.character(tax$Taxa[1:11438]))
> phylomatic_local(taxa,path="E:/Planilhas R/phylomatic-ws")
> Error in file(con, "r") : cannot open the connection
> In addition: Warning messages:
> 1: running command 'echo 'taxa=fabaceae/abarema/abarema_cochliacarpos
> fabaceae/abarema/abarema_langsdorffii
> fabaceae/abarema/abarema_villosa
> salicaceae/abatia/abatia_americana
> cyperaceae/abildgaardia/abildgaardia_baeothryon
> cyperaceae/abildgaardia/abildgaardia_ovata
> cyperaceae/abildgaardia/abildgaardia_papillosa
> xyridaceae/abolboda/abolboda_egleri
> xyridaceae/abolboda/abolboda_poarchon
> xyridaceae/abolboda/abolboda_pulchella
> fabaceae/abrus/abrus_fruticulosus
> fabaceae/abrus/abrus_precatorius
> fabaceae/abrus/abrus_pulchellus
> menispermaceae/abuta/abuta_grandifolia
> malvaceae/abutilon/abutilon_inaequilaterum
> malvaceae/abutilon/abutilon_pauciflorum
> malvaceae/abutilon/abutilon_ramiflorum
> malvaceae/abutilon/abutilon_umbelliflorum
> rosaceae/acaena/acaena_eupatoria
> euphorbiaceae/acalypha/acalypha_amblyodonta
> euphorbiaceae/acalypha/acalypha_brasiliensis
> euphorbiaceae/acalypha/acalypha_chorisandra
> euphorbiaceae/acalypha/acalypha_claussenii
> euphorbiaceae/acalypha/acalypha_communis
> euphorbiaceae/acalypha/a [... truncated] 
> 2: In file(con, "r") :
>   cannot open file 'out.new': No such file or directory

Now I had other problem.

Thanks, regards!

**Comment by sckott** [comment]
Glad you got awk installed. That looks like a problem with file not being found correctly. I'll test on windows to see what's going wrong

**Comment by sckott** [comment]
@aeltonbg okay, try again after reinstalling `devtools::install_github("ropensci/brranching")` 
- a fix was made in phylomatic https://github.com/camwebb/phylomatic-ws/issues/3 so we can do very large input taxon lists locally - Do download `phylomatic-ws` again
- `phylomatic_local()` improved, uses the new `phylomatic-ws`, and works better. 
- after trying this, let me know if you still have the problem above in https://github.com/ropensci/brranching/issues/13#issuecomment-187904270

**Comment by aeltonbg** [comment]
@sckott I tested again. And now I had other error!

> spp<-unique(as.character(tax$Taxa[1:11438]))
> head(spp)
> [1] "Abarema cochliacarpos"   "Abarema langsdorffii"    "Abarema villosa"         "Abatia americana"        "Abildgaardia baeothryon"
> [6] "Abildgaardia ovata"  
> (tree<-phylomatic_local(spp,path="E:/phylomatic-ws"))
> preparing names...
> processing with phylomatic...

Phylogenetic tree with 0 tips and  internal nodes.

Tip labels:
NULL
Error in tabulate(phy$edge[, 1]) : 'bin' deve ser numérico ou um fator
In addition: Warning message:
running command 'cat E:/phylomatic-ws/file193c60b51835.txt | ./pmws > E:/phylomatic-ws/out.new' had status 127 

> (tree<-phylomatic_local(spp,path="E:/phylomatic-ws"))
> preparing names...
> processing with phylomatic...

Phylogenetic tree with 0 tips and  internal nodes.

Tip labels:
NULL
Error in tabulate(phy$edge[, 1]) : 'bin' deve ser numérico ou um fator
In addition: Warning message:
running command 'cat E:/phylomatic-ws/file193c9d6586c.txt | ./pmws > E:/phylomatic-ws/out.new' had status 127

So, I really didn't know!

Thanks

**Comment by aeltonbg** [comment]
@sckott just translating

Error in tabulate(phy$edge[, 1]) : 'bin' deve ser numérico ou um fator
Error in tabulate(phy$edge[, 1]) : 'bin' need to be numeric or factor

thanks

**Comment by sckott** [comment]
I'll have a look. I guess I really need to try this on windows, i'll try to get to that today

**Comment by sckott** [comment]
i tried again on this - it does seem there is an option when installing Rtools to add Rtools to your path, so that awk can be found by R/Rstudio 

That still doesn't solve the problem of getting awk to work, not solved that yet

**Comment by sckott** [comment]
closing this as there is a solution that works at least in some cases, 

opened a new issue to make sure I fix this on windows - see #17

**Comment by oolonek** [comment]
Dear sckott,

Just stumbled upon this thread at the moment.
Using Mac (10.11) and R studio here so no Rtools involved.
Also trying to run phylomatic on >6000 species ... Not working.
Installed gawk (had awk allready) and phylomatic_local but still get this issue:

`> tree <- phylomatic_local(taxa = taxa,path="/Users/pma/phylomatic-ws/")
preparing names...
processing with phylomatic...
sh: ./pmws: ./gawk: bad interpreter: No such file or directory
cat: stdout: Broken pipe
Error in matrix(NA, sum(text == "(") + sum(text == ","), 2) : 
  invalid 'nrow' value (too large or NA)`

Looks like gawk is not found and thus returns the same issue as when I use the classical phylomatic 

How can I solve this ?

Thanks

**Comment by oolonek** [comment]
Ok. 

Works intsalling devtools::install_github("ropensci/brranching@phylocom-pkg")
As specified here https://github.com/ropensci/brranching/issues/17


Edit : actually works if taxa < 4100 or so .... Will never complete if taxa number > 6000
So I guess I should use the local phylomatic but then come back to same error as described in the above message ...

**Comment by sckott** [comment]
sorry for the delay @oolonek was on vacation last week  - thanks for raising this issue. 

Glad you got the install from the `phylocom-pkg` branch

Did you try the function `phylomatic_local2` ? that is a new version of `phylomatic_local` that uses our new pkg `phylocomr` (not yet on CRAN) https://github.com/ropensci/phylocomr that is a R binding to the C library behind the Phylocom command line tool - e.g., try 

```r
spp <- names_list("species", 7000)
(tree <- phylomatic_local2(spp))
preparing names...
processing with phylomatic...

Phylogenetic tree with 6127 tips and 1626 internal nodes.

Tip labels:
	sagina_revelieri, sagina_bryoides, minuartia_drummondii, minuartia_propinqua, cerastium_smolikanum, cerastium_crassiusculum, ...
Node labels:
	euphyllophyte, seedplants, nymphaeales_to_asterales, austrobaileyales_to_asterales, magnoliales_to_asterales, poales_to_asterales, ...

Rooted; includes branch lengths.
```

**Comment by oolonek** [comment]
@sckott  thanks for the feedback !

Could make it work with phylomatic_local after adding gawk and gawk4.1.1 and igawk in phylomatic-ws folder.
Using phylomatic_local2 as you suggested is even faster, works like a charm !

Thanks

**Comment by sckott** [comment]
great
