### ISSUE TITLE
Get tree from abundance table

### ISSUE THREAD

**Issue by davidvilanova** [ropensci/brranching#28]
Hi,
I have an abundance table (each row corresponds to a taxa). I would like to get the tree (newick default format) of the table. 
The table contains bacteria, archeae and fungi. 

How can i get a phylogenetic tree from this table (the original table has around 600 rows)??
The idea is to use the tree for further analysis using R.
 

```
SampleA    Phylum               Class          Order               Family           Genus                 Species
12           Actinobacteria     Actinomycetales Actinobacteria     Actinomycetaceae     Actinomyces Actinomyces neuii
 3             Actinobacteria     Actinomycetales Actinobacteria     Actinomycetaceae     Actinomyces   Unknown
34            Actinobacteria     Corynebacteriales Actinobacteria   Corynebacteriaceae Corynebacterium  Corynebacterium sp. HMSC064E10
59            Actinobacteria     Corynebacteriales Actinobacteria   Corynebacteriaceae Corynebacterium  Corynebacterium aquilae
965          Actinobacteria     Propionibacteriales Actinobacteria Propionibacteriaceae   Tessaracoccus Tessaracoccus sp. NSG39
44           Proteobacteria     Unknown               Unknown              Unknown         Unknown        Unknown
```

**Comment by sckott** [comment]
thx for your question @davidvilanova !

Is the idea that you just want to input a data.frame to a function and it does all the work?  Or are you thinking you're happy to pull out some names from the table as needed?

**Comment by davidvilanova** [comment]
I need a phylogentic tree that incorporates branches length. I would normally align sequences and do it from a sequence alignment. In this case i ca´t do it because taxonomy comes from single copy genes. I was thinking to compute a distance matrix from there and generate the tree from there.
My data frame contains 30 samples and 500 rows. Not all rows have annotations at the species level. Programatically speaking i don´tmind if you have a function that can be easily for used for thus purpose or if it will be better to have a distance matrix ??

**Comment by sckott** [comment]
Hmm, the package's goal is to fetch phylogenies from data sources on the web, currently only Phylomatic (which is focused only on plants) - where the inputs are taxonomic names. 

I am interested in more data sources (see https://github.com/ropensci/brranching/issues?q=is%3Aissue+is%3Aopen+label%3Adata-source), but haven't done any yet. 

It sounds like you actually have the sequence data, and want to build a phylogeny from your own data (or am I wrong on that?)

**Comment by davidvilanova** [comment]
The basic question is how do you get a phylogenetic tree from a set of single copy genes ?

**Comment by sckott** [comment]
I wish I could help!  I was trained as an ecologist - so i'm not sure I can help
