### ISSUE TITLE
Add a vignette

### ISSUE THREAD

**Issue by sckott** [ropensci/brranching#31]
This package needs more documentation!  Help out the community by contributing a vignette. If you don't know what a vignette is, check out http://r-pkgs.had.co.nz/vignettes.html for an introduction.  

If you aren't sure how to contribute on github checkout https://github.com/ropensci/brranching/blob/master/.github/CONTRIBUTING.md 

Keep in mind our code of conduct https://github.com/ropensci/brranching/blob/master/CONDUCT.md

**Comment by fozy81** [comment]
See pull [request](https://github.com/fozy81/brranching/commit/4fbd162f9852988f1bc257482f169e59c8b9af89) for vignette. Includes slightly updated version of the package README file. :smile:
