### ISSUE TITLE
error in running phylomatic_local via brranching

### ISSUE THREAD

**Issue by benpaozaitianshan** [ropensci/brranching#37]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>
Hello, Scott,  I am using "brranching" to  building phylomatic tree with storedtree slik2015 (new phylogeny in  slik et al. 2018),  I tried to set the path, but there is an error: "object 'tree' not found". The format of tree is newick.  So, I request that could you add the slik2015 (slik et al. 2018) in the the "brranching"?

**Comment by sckott** [comment]
please include your session info as requested. if you aren't sure how to do this. start R, load `brranching`, then run `sessionInfo()` then paste in the output of that function into a comment here.

**Comment by sckott** [comment]
also, please share the code that was tried, and the error that resulted. share the phylogeny as well by attaching the file, or email to me at myrmecocystus@gmail.com

**Comment by sckott** [comment]
closing as no response
