### ISSUE TITLE
Maintenance status / help needed?

### ISSUE THREAD

**Issue by maelle** [ropensci/brranching#47]
:wave: @LunaSare!

Do you still intend to become this package's maintainer?

If so do you need any help? For instance an aspect where you'd appreciate some tips, contributions, a PR review? Do you need an invitation to our friendly Slack workspace?

**Comment by LunaSare** [comment]
Hi @maelle! Thanks so much for your message. I think joining the Slack channel will be helpful for sure. Is there a link I can follow for that?

**Comment by maelle** [comment]
Let me ping @ropensci/admin

**Comment by yabellini** [comment]
@LunaSare is in our Slack now :-)
